name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - '*'
    - '!badges'


jobs:
  build:
    name: FM4SE-Christmas | Alloy Encoding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout Starter Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Display Java version
        run: java -version
            
      - name: Grading
        uses: education/autograding@v1
        id: autograder
        continue-on-error: true
        
      # switch to badges branch
      - run: git checkout badges || git checkout -b badges

      # commit and push badges if badges have changed
      - name: Commit changes to points bar
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 'report.md'
          git commit -m "Add/Update report" || exit 0
          git push -f origin badges